# On commit: checks build succeeds

name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - name: Build
        uses: CultureHQ/actions-yarn@master
        with:
          args: tsc
      - name: Lint fix TS emits
        uses: CultureHQ/actions-yarn@master
        with:
          args: pre-commit:fix-ts-emits

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Jamie Gerrard Lievesley
          author_email: jamie@jamiegl.co.uk
          message: "Added generated TypeScript declarations"
          add: "*.d.ts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
